service: media-service

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
      Resource: "arn:aws:s3:::*"

functions:
  token:
    handler: src/lambda/auth/handler.token
    events:
      - http:
          path: token
          method: post

  file:
    handler: src/lambda/files/handler.file
    events:
      - http:
          path: file/{path}/{type}/{id}/{filename}
          method: get
          cors: true

  upload:
    handler: src/lambda/middlewares/validators/upload.validate
    events:
      - http:
          path: upload
          method: post

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: my-example-bucket
        AccessControl: PublicReadWrite
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html